djsite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from account.views import Login, Register, activate

urlpatterns = [
    path('', include('myapp.urls')),
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path("login/", Login.as_view(), name="login"),

    path('register/', Register.as_view(), name='register'),
    #re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', activate, name='activate'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', activate, name='activate'),

    path('activate/<uidb64>/<token>/', activate, name='activate'),
    path('comment/', include('comment.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),



]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.urls import path
from .views import (ArticleList, ArticleDetail,
                     CateogryList, AuthorList, 
                     ArticleDetailPreview,SearchList)

app_name='myapp'
urlpatterns = [
    path('', ArticleList.as_view(), name='home'),
    path('article/<slug:slug>',ArticleDetail.as_view(), name='article_detail'),
    path('preview/<int:pk>',ArticleDetailPreview.as_view(), name='preview'),
    path('category/<slug:slug>',CateogryList.as_view(), name='category'),
    path('author/<slug:username>',AuthorList.as_view(), name='author'),

    path('search/', SearchList.as_view(), name='search'),
    path('search/page/<int:page>', SearchList.as_view(), name="search")

]

myapp/models.py
from django.db import models
from account.models import User
from django.utils import timezone
from extensions.utils import jalali_converter
from django.utils.html import format_html
from django.urls import reverse

from django.contrib.contenttypes.fields import GenericRelation
from comment.models import Comment




# Create your models here.

#MiddleWares
class IPAddress(models.Model):
    ip_address = models.GenericIPAddressField(verbose_name='آدرس آی پی')
    class Meta:
        verbose_name = 'آی پی آدرس'
        verbose_name_plural = 'آی پی آدرس ها'
        


# Managers

# published articles for use in templates
class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status='p')
    
# active categories for use in category_navbar.html template
class CategoryManager(models.Manager):
    def active(self):
        return self.filter(status=True)
    
class Category(models.Model):
    
    parent = models.ForeignKey('self', default=None, null=True, blank=True, on_delete=models.SET_NULL, related_name='children', verbose_name='زیر دسته')
    title = models.CharField(max_length=200, verbose_name='عنوان دسته بندی')
    slug = models.SlugField(max_length=100, unique=True, verbose_name='آدرس دسته بندی')
    status = models.BooleanField(default=True, verbose_name='آیا نمایش داده شود؟')
    position = models.IntegerField(verbose_name='پوزیشن')

    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها'
        ordering = ['parent__id', 'position']

    def __str__(self):
        return self.title
    objects = CategoryManager()


    
class Article(models.Model):
    STATIUS_CHOICES = (
        ("d", "پیش نویس"),       # draft
        ("p", "منتشر شده"),      # publish
        ("l", "در حال بررسی"),   # lock
        ("b", "برگشت داده شده"), # back
    )
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='articles', verbose_name='نویسنده')
    title = models.CharField(max_length=200, verbose_name='عنوان')
    slug = models.SlugField(max_length=100, unique=True, verbose_name='آدرس مقاله')
    category = models.ManyToManyField(Category, verbose_name='دسته بندی', related_name='articles')
    description = models.TextField(verbose_name='محتوا')
    thumbnail = models.ImageField(upload_to="images", verbose_name='تصویر')
    publish = models.DateTimeField(default=timezone.now, verbose_name='زمان انتشار')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    is_special = models.BooleanField(default=False, verbose_name='مقاله ویژه')
    status = models.CharField(max_length=1,choices=STATIUS_CHOICES, verbose_name='وضعیت')
    comments = GenericRelation(Comment)
    hits = models.ManyToManyField(IPAddress, through="ArticleHit", blank=True, related_name="hits", verbose_name="بازدیدها") # relation among ip_addresses and articles



    # class Article setting
    class Meta:
        verbose_name = 'مقاله'
        verbose_name_plural = 'مقالات'
        ordering = ['-publish']

    def __str__(self):
        return self.title
    

    def get_absolute_url(self):
        return reverse("account:home")
    
    def jpublish(self):
        return jalali_converter(self.publish)
    
    jpublish.short_description = 'زمان انتشار'
    
    def thumbnail_tag(self):
        return format_html("<img width = 100 style = 'border-radius:5px;' src='{}'>".format(self.thumbnail.url))
    thumbnail_tag.short_description = 'تصویر'

    
    def category_to_str(self):
        return " ,".join([category.title for category in self.category.active()])
    category_to_str.short_description = ' دسته بندی'

    
    objects = ArticleManager()


class ArticleHit(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    ip_address = models.ForeignKey(IPAddress, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

comment/views/base.py
from django.views.generic import FormView

from comment.conf import settings
from comment.context import DABContext
from comment.responses import DABResponseData
from comment.messages import EmailInfo
from comment.service.email import DABEmailService
from comment.forms import CommentForm


class BaseCommentView(FormView, DABResponseData):
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = context.pop('form')
        context.update(DABContext(self.request))
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


class CommentCreateMixin(BaseCommentView):
    email_service = None

    def _initialize_email_service(self, comment, request):
        self.email_service = DABEmailService(comment, request)

    def _send_notification_to_followers(self, comment, request):
        if settings.COMMENT_ALLOW_SUBSCRIPTION:
            self._initialize_email_service(comment, request)
            self.email_service.send_notification_to_followers()

    def perform_save(self, comment, request):
        comment.save()
        self._send_notification_to_followers(comment, request)
        comment.refresh_from_db()
        return comment

    def _handle_anonymous(self, comment, request, api=False):
        self._initialize_email_service(comment, request)
        self.email_service.send_confirmation_request(api=api)
        self.anonymous = True
        self.msg = EmailInfo.CONFIRMATION_SENT

    def perform_create(self, comment, request, api=False):
        if settings.COMMENT_ALLOW_ANONYMOUS and not comment.user:
            self._handle_anonymous(comment, request, api)
        else:
            comment = self.perform_save(comment, request)
        return comment

myapp/views.py
from django.views.generic import ListView, DeleteView
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from .models import Article, Category
from account.models import User
from account.mixins import AuthorAccessMixin
from django.db.models import Q





# generic display Views: ListView, DeleteView

# Model >> ArticleList get data from Article model
# View >> ArticleList is list of articles
# Template >> home.html

# ArticleList is for show list of articles in home page
class ArticleList(ListView):
    # model = Article
    # context_object_name = "articles"
    queryset = Article.objects.published()
    template_name = "myapp/home.html"
    paginate_by = 2

class ArticleDetail(DeleteView):
    template_name = "myapp/article_detail.html"

    def get_object(self):
        slug = self.kwargs.get('slug')
        article = get_object_or_404(Article.objects.published(), slug=slug)
        ip_address = self.request.user.ip_address
        if ip_address not in article.hits.all():
            article.hits.add(ip_address)
        return article
     
# see preview of article before publish in website
class ArticleDetailPreview(AuthorAccessMixin,  DeleteView):
    template_name = "myapp/article_detail.html"

    def get_object(self):
        pk = self.kwargs.get('pk')
        return get_object_or_404(Article, pk=pk)
    

# paginator for articles and categories
'''def category(request, slug):
    category = get_object_or_404(Category, slug=slug, status=True)
    articles_list = category.articles.published()
    paginator = Paginator(articles_list, 2)  # Show 2 article per page.
    page_number = request.GET.get("page")
    articles = paginator.get_page(page_number)

    context = {
        "category": category,
        "articles": articles,
    }
    return render(request, 'myapp/category.html', context)
''' 

class CateogryList(ListView):
    template_name = "myapp/category.html"
    paginate_by = 2
    def get_queryset(self):
        global category # for next function
        slug = self.kwargs.get('slug')
        category = get_object_or_404(Category.objects.active(), slug=slug)
        return category.articles.published()
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = category
        return context
    

class AuthorList(ListView):
    template_name = "myapp/author.html"
    paginate_by = 2
    def get_queryset(self):
        global author
        username = self.kwargs.get('username')
        author = get_object_or_404(User ,username=username)
        return author.articles.published()
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author'] = author
        return context
    

#search box
class SearchList(ListView):
    template_name = "myapp/search_list.html"
    paginate_by = 2
    def get_queryset(self):
        search = self.request.GET.get('q')
        return Article.objects.filter(Q(description__icontains=search) | Q(title__icontains=search))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search'] = self.request.GET.get('q')
        return context

templates/myapp/article_detail.html
{% extends 'myapp/base.html' %}
{% load comment_tags %}
{% load ratings %}
{% load base_tags %}
{% load humanize %}
{% include 'registration:login.html' %}


{% block title %} | {{object.title}}{% endblock %}
{% block main %}

        <!-- Page Header-->
        <header class="masthead" style="background-image: url('{{object.thumbnail.url}}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1 style="text-align: center;">{{object.title}}</h1> 
                            {% if article.is_special %}
                                <span style="font-size: 14px; color: red;">ویژه</span>
                                <br>
                            {% endif %}
                            <!--<time>{{object.jpublish}}</time>-->
                            <time>{{object.publish | naturaltime}}</time>

                            <div>{% ratings object %}</div>
                            <div> بازدیدها: {{object.hits.count}}</div>

                            <!-- <span class="subheading">سامانه مهندسی کامپیوتر</span> -->
                        </div>
                    </div>
                </div>
            </div>
        </header>

        <aside>
                {% popular_articles %}            
                {% hot_articles %}
        </aside>

            <!-- Post Content-->
            <article class="mb-4">
                <div class="container px-4 px-lg-5">
                    <div class="row gx-4 gx-lg-5 justify-content-center">
                        <div class="col-md-10 col-lg-8 col-xl-7 text-justify">
                            
                            {% if object.is_special %}
                                {% if user.is_authenticated or user.is_special or user == object.author or user.is_superuser%}
                                    {{object.description|safe}}
                                {% else %}
                                    {{article.description|striptags|truncatewords:25}}
                                    <p class="alert alert-warning">این مقاله ویژه است  برای مشاهده آن به سایت  
                                        {% url 'login' as login_url %}
                                        <a class="alert-link" style="text-decoration: none;" href="{{ login_url }}" target="_blank">
                                            ورود
                                        </a>
                                    </p>
                                {% endif %}
                            {% else %}
                               {{object.description|safe}}
                            {% endif %}
                            
                            {% render_comments object request %} 
                            {% include_bootstrap %} 

                        </div>
                    </div>
                </div>
            </article>
{% endblock %}

templates/myapp/author.html
{% extends 'myapp/list.html' %}

{% block header%}
    <h3 class="alert alert-primary text-center">نویسنده: {{author.get_full_name}}</h3>
{% endblock %}

{% block previous_page_url %}
    {% url 'myapp:author' author.username %}?page={{page_obj.previous_page_number}}
{% endblock %}

{% block next_page_url %}
    {% url 'myapp:author' author.username %}?page={{page_obj.next_page_number}}
{% endblock %}

templates/myapp/base.html
{% load static %}
{% load base_tags %}
<!DOCTYPE html>
<html lang="fa">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% site_name %} {% block title %} {% endblock %} </title> <!-- سامانه مهندسی کامپیوتر  = -->
        <link rel="icon" type="image/x-icon" href="{% static 'myapp/assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'myapp/css/styles.css' %}" rel="stylesheet"/>
        <link href="{% static 'myapp/css/rtl.css' %}" rel="stylesheet" />


        <!-- added codes for rating app -->
        <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
        <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>




        {% block custome-header %}
        {% endblock %}
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <!-- <a class="navbar-brand" href="{% url 'myapp:home'%}">سامانه کامپیوتر</a> -->
                 <!--<<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    لیست
                    <i class="fas fa-bars"></i>
                </button>-->
                {% category_navbar %}
            </div>
        </nav>

        {% block main %}
        {% endblock %}
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">

                            <li class="list-inline-item">
                                <a href="https://x.com/smomeninasab" target="_blank">
                                  <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fas fa-xmark fa-stack-1x fa-inverse"></i>
                                  </span>
                                </a>
                            </li>

                              <li class="list-inline-item">
                                <a href="https://t.me/SirousMomeniNasab" target="_blank">
                                  <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-telegram fa-stack-1x fa-inverse"></i>
                                  </span>
                                </a>
                              </li>

                              <li class="list-inline-item">
                                <a href="https://www.instagram.com/sirousmomeninasab" target="_blank">
                                  <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-instagram fa-stack-1x fa-inverse"></i>
                                  </span>
                                </a>
                              </li>
                        </ul>
                        <!-- <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div> -->
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{%static 'myapp/js/scripts.js'%}"></script>
    </body>
</html>

templates/myapp/category.html
{% extends 'myapp/list.html' %}

{% block header%}
    <h3 class="alert alert-primary text-center" style="font-family: Sahel;">دسته بندی: {{category.title}}</h3>
{% endblock %}

{% block previous_page_url %}
    {% url 'myapp:category' category.slug%}?page={{page_obj.previous_page_number}}
{% endblock %}

{% block next_page_url %}
    {% url 'myapp:category' category.slug%}?page={{page_obj.next_page_number}}
{% endblock %}

templates/myapp/home.html
{% extends 'myapp/list.html' %}

{% block header%}
{% endblock %}

{% block previous_page_url %}
    {% url 'myapp:home' %}?page={{page_obj.previous_page_number}}
{% endblock %}

{% block next_page_url %}
    {% url 'myapp:home' %}?page={{page_obj.next_page_number}}
{% endblock %}

templates/myapp/list.html
{% extends 'myapp/base.html' %}
{% load static %}
{% load base_tags %}
{% load ratings %}
{% load humanize %}

{%block main%}


        <!-- Page Header-->
        <header class="masthead" style="background-image: url('{% static 'myapp/assets/img/home-bg.jpg' %}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1> {% site_name %} </h1>
                            <!--  <span class="subheading">سامانه مهندسی کامپیوتر </span> -->
                        </div>
                    </div>
                </div>
            </div>
        </header>

        <!-- Main Content-->
        <div class="container px-4 px-lg-5" >
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7" style="font-family: Sahel;">
                    {% block header %}{% endblock %}
                    <aside>
                        {% popular_articles %}
                        {% hot_articles %}
                    </aside>

                    

                    {% for article in object_list %}
                    <!-- Post preview-->
                    <div class="post-preview">
                        <a href="{% url 'myapp:article_detail' article.slug%}"> 
                            <h2 class="post-title">
                                {{article.title}}
                                {% if article.is_special %}
                                    <span style="font-size: 14px; color: red;">ویژه</span>
                                {% endif %}
                            </h2>

                            <div>{% ratings article %}</div> 

                            <h3 class="post-subtitle">{{article.description|striptags|safe|truncatewords:25}}</h3>
                        </a>
                        <p class="post-meta">
                            نوشته شده توسط
                            <a href="{% url 'myapp:author' article.author %}">
                                {{article.author.get_full_name}} 
                            </a>
                            <!--{{article.jpublish}}-->
                            {{article.publish | naturaltime}}

                        </p>

                        <div> 
                            {%for cat in article.category.active%}
                                <a href="{% url 'myapp:category' cat.slug %}"> #{{cat.title}} </a>
                            {%endfor%}
                        </div>

                        <div> بازدیدها: {{article.hits.count}}</div>

                     </div style="myfont" >
                     <!-- Divider-->
                     <hr class="my-4" />
                     {% empty %}
                     <p>متاسفانه محتوایی برای نمایش وجود ندارد.</p>
                    {% endfor %}
                
                    <!-- Pager-->
                     {% if is_paginated %}
                    <!-- Pager -->

                        <div class="pagination-container" style="text-align: center; width: 100%; margin: 20px auto;">
                        {% if is_paginated %}
                            {% if page_obj.has_previous %}
                                <a class="btn btn-primary text-uppercase" style="font-family:Sahel" href="{% block previous_page_url %}{% endblock %}">
                                ► پست های جدید
                                </a>
                            {% endif %}
    
                            {% if page_obj.has_next%}
                                <a class="btn btn-primary text-uppercase" style="font-family:Sahel" href="{% block next_page_url %}{% endblock %}">
                                پست های قدیمی ◄
                                </a>
                            {% endif %}
                        {% endif %}
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
{%endblock%}

templates/myapp/search_list.html
{% extends 'myapp/list.html' %}

{% block header%}
    <h3 class="alert alert-primary text-center">جستجو: {{search}}</h3>
{% endblock %}

{% block previous_page_url %}
    {% url 'myapp:search'  %}?page={{page_obj.previous_page_number}}?q={{search}}
{% endblock %}

{% block next_page_url %}
    {% url 'myapp:search' %}?page={{page_obj.next_page_number}}?q={{search}}
{% endblock %}